This is the updated file of Q&As
in-tech-gration/WDX-180 pull request #17
Opened 2023-10-20 08:37 UTC by vagelisx

2023-10-20 12:42 UTC, patric94 commented
Good job @vagelisx !
If you have the time, could you please do the following changes?
- Add any questions added after your PR
- Please replace `Question:` with `Q:` and `Answer:` with `A:`
- Please add after every Q&A a horrizontal line (three '-') to increase readability of document
Thanks a lo!

2023-10-22 17:31 UTC, kostasx commented
@patric94 @vagelisx I've updated the requirements and we can either use **Q: A:** or **Question: Answer:** or even **QUESTION: ANSWER:** for separating the Q&A. So, there's no need to change the **Question: Answer:**. The parser will take care of the lowercase/uppercase and various formats. :)

2023-10-22 22:12 UTC, vagelisx commented
> Good job @vagelisx ! If you have the time, could you please do the following changes?
> 
>     * Add any questions added after your PR
> 
>     * Please replace `Question:` with `Q:` and `Answer:` with `A:`
> 
>     * Please add after every Q&A a horrizontal line (three '-') to increase readability of document
>       Thanks a lo!

@patric94 cc @kostax : I made the changes anyway to practice the git commands and processes. I will keep my eye on the Q&A's next week, you can continue working on more demandin issues.

2023-10-23 08:18 UTC, kostasx commented
@vagelisx Please go through the [git diff](https://github.com/in-tech-gration/WDX-180/pull/17/files) carefully and fix the content that contains wrong replacements of Q. 

As I mentioned, it's not necessary from now on to stick to Q/A. Question/Answer or QUESTION/ANSWER will do just fine.

Don't forget to add "---" between each question:

```markdown
Q: Why I am here?
A: Don't know

---

Q: What is the meaning of it all?
A: 42
```

2023-10-30 09:53 UTC, kostasx requested changes

2023-10-30 09:53 UTC, kostasx commented on staff/archive/slido.md
> +  Q: I have a Q regarding VS Code. I don't see any day 04 exercises in my curriculum or user. How do I complete the assignment? The only thing I see under day 04 is README.md
"Q: I have a Q regarding VS Code." @vagelisx

2023-10-30 10:50 UTC, kostasx requested changes

2023-10-30 10:50 UTC, kostasx commented on staff/archive/slido.md
> + A: This Q was covered extensively on the Q&A live section: https://www.youtube.com/watch?v=mhUiYaZjEvU&list=PLdo7hJB0agEkkLFrssQCGWnV08Q50X_M0&index=5
Another one here. @vagelisx

2023-11-02 10:32 UTC, kostasx commented
Thank you @vagelisx.

2023-11-02 10:32 UTC, closed without merging